<h1>Fase 1:Data Cleaning</h1>

In [1]:
#Importando Bibliotecas
import pandas as pd
import numpy as np
from unicodedata import normalize

In [2]:
# Unindo os bancos de dados.
def dataframes():
    
    # Criando dataframe vazio
    df_concat = pd.DataFrame()
    
    # Loop utilizado para percorrer todos os arquivos csv's.
    for i in range(1,32):
        
        #Condição utilizada para saltar o dia 6 que não teve despesa.
        if i < 10 and i != 6:
            
            # Variável que armazena o nome do arquivo csv.
            path = '2019010{}_Despesas_Pagamento.csv'.format(str(i))
            df = pd.read_csv(path,encoding = 'iso-8859-1',sep = ';')
            
            # Condição que só pega os arquivos com despesas, as outras são descartadas.
            if df.shape[0] > 0:
                
                # Concatenando os dataframes um a um.
                df_concat = pd.concat([df_concat,df])
            #print('Tamanho dos dados do dia {}: {}'.format(i,df.shape))
            #print('Tamanho concatenação: {}'.format(df_concat.shape))
            
        # Mesma ideia nessa condição, mas agora excluindo os dias 20,26 e 27.
        elif i >= 10 and i != 20 and i != 26 and i != 27:
            path = '201901{}_Despesas_Pagamento.csv'.format(str(i))
            df = pd.read_csv(path, encoding = 'iso-8859-1',sep = ';')
            if df.shape[0] > 0:
                df_concat = pd.concat([df_concat,df])
            #print('Tamanho dos dados do dia {}: {}'.format(i,df.shape))
            #print('Tamanho concatenação: {}'.format(df_concat.shape))
    #print('União {}'.format(df_concat.shape))
    
    # Retornando o dataframe concatenado
    return df_concat

df = dataframes()

C:\Users\Matheus\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3185: DtypeWarning: Columns (15,19,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):

<h3>Problemas econtrados:</h3>
    
* ParserError: ',' expected after '"': Resolvido alterando o parâmetro do delimitador do arquivo para ';'.
* UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte: Resolvido mudando a codificação utf-8 para iso-8859-1 que é a codificação dos caracteres latinos.

In [3]:
# Visualização inicial de como ficou o dataframe.
df.head()

,Código Pagamento,Código Pagamento Resumido,Data Emissão,Código Tipo Documento,Tipo Documento,Tipo OB,Extraorçamentário,Código Órgão Superior,Órgão Superior,Código Órgão,...,Categoria de Despesa,Código Grupo de Despesa,Grupo de Despesa,Código Modalidade de Aplicação,Modalidade de Aplicação,Código Elemento de Despesa,Elemento de Despesa,Valor Original do Pagamento,Valor do Pagamento Convertido pra R$,Valor Utilizado na Conversão
0,155001152752019NS004348,2019NS004348,01/01/2019,NS,Nota de Lançamento de Sistema,Não se aplica,NÃO,26000,MINISTERIO DA EDUCACAO,26294,...,DESPESAS CORRENTES,3,OUTRAS DESPESAS CORRENTES,90,APLICACOES DIRETAS,MU,Múltiplo,"2000,00","2000,00","1,0000"
0,180006000012019OB800099,2019OB800099,02/01/2019,OB,Ordem Bancária,OBC/OBB PARA TERCEIROS EM OUTROS BANCOS,NÃO,55000,MINISTERIO DA CIDADANIA,55000,...,DESPESAS DE CAPITAL,4,INVESTIMENTOS,40,TRANSFERENCIAS A MUNICIPIOS,42,AUXILIOS - FUNDO A FUNDO,"48750,00","48750,00","1,0000"
1,440075000012019DF800002,2019DF800002,02/01/2019,DF,Documento de Arrecadação Federal,Não se aplica,NÃO,22000,"MINIST. DA AGRICUL.,PECUARIA E ABASTECIMENTO",44208,...,DESPESAS CORRENTES,3,OUTRAS DESPESAS CORRENTES,90,APLICACOES DIRETAS,39,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,"50,03","50,03","1,0000"
2,180006000012019OB800271,2019OB800271,02/01/2019,OB,Ordem Bancária,OBC/OBB PARA TERCEIROS EM OUTROS BANCOS,NÃO,55000,MINISTERIO DA CIDADANIA,55000,...,DESPESAS DE CAPITAL,4,INVESTIMENTOS,40,TRANSFERENCIAS A MUNICIPIOS,42,AUXILIOS - FUNDO A FUNDO,"204750,00","204750,00","1,0000"
3,158591264272019OB800001,2019OB800001,02/01/2019,OB,Ordem Bancária,OBS DE OUTRAS CONTAS PARA CONTA UNICA,NÃO,26000,MINISTERIO DA EDUCACAO,26427,...,Sem informação,-1,Sem informação,-1,Sem informação,-1,Sem informação,"-100,00","-100,00","1,0000"

In [4]:
# Informações sobre cada coluna
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 388884 entries, 0 to 25850
Data columns (total 30 columns):
Código Pagamento                        388884 non-null object
Código Pagamento Resumido               388884 non-null object
Data Emissão                            388884 non-null object
Código Tipo Documento                   388884 non-null object
Tipo Documento                          388884 non-null object
Tipo OB                                 388884 non-null object
Extraorçamentário                       388884 non-null object
Código Órgão Superior                   388884 non-null int64
Órgão Superior                          388884 non-null object
Código Órgão                            388884 non-null int64
Órgão                                   388884 non-null object
Código Unidade Gestora                  388884 non-null int64
Unidade Gestora                         388884 non-null object
Código Gestão                           388884 non-null int64
Gestão                                  388884 non-null object
Código Favorecido                       388884 non-null object
Favorecido                              388884 non-null object
Observação                              388884 non-null object
Processo                                357946 non-null object
Código Categoria de Despesa             388884 non-null object
Categoria de Despesa                    388884 non-null object
Código Grupo de Despesa                 388884 non-null object
Grupo de Despesa                        388884 non-null object
Código Modalidade de Aplicação          388884 non-null object
Modalidade de Aplicação                 388884 non-null object
Código Elemento de Despesa              388884 non-null object
Elemento de Despesa                     388884 non-null object
Valor Original do Pagamento             388884 non-null object
Valor do Pagamento Convertido pra R$    388884 non-null object
Valor Utilizado na Conversão            388884 non-null object
dtypes: int64(4), object(26)
memory usage: 92.0+ MB

In [5]:
# Alterando os nomes das colunas para facilitar sua manipulação

# Criando dicionario comprehensions para remover os acentos e escrever apenas a primeira letra como maiúscula.
# Na forma de dicionário para facilitar quando passar para o método rename -> {'Nome antigo':'Nome modificado'}
nome_colunas_modif = {val : normalize('NFKD', val).encode('ASCII','ignore').decode('ASCII').replace(' ','_').capitalize() for index,val in enumerate(df.columns)}

# Renomeando todas as colunas do dataframe
df = df.rename(index=str,columns = nome_colunas_modif)

In [6]:
# Visualizando modificações
df.head()

,Codigo_pagamento,Codigo_pagamento_resumido,Data_emissao,Codigo_tipo_documento,Tipo_documento,Tipo_ob,Extraorcamentario,Codigo_orgao_superior,Orgao_superior,Codigo_orgao,...,Categoria_de_despesa,Codigo_grupo_de_despesa,Grupo_de_despesa,Codigo_modalidade_de_aplicacao,Modalidade_de_aplicacao,Codigo_elemento_de_despesa,Elemento_de_despesa,Valor_original_do_pagamento,Valor_do_pagamento_convertido_pra_r$,Valor_utilizado_na_conversao
0,155001152752019NS004348,2019NS004348,01/01/2019,NS,Nota de Lançamento de Sistema,Não se aplica,NÃO,26000,MINISTERIO DA EDUCACAO,26294,...,DESPESAS CORRENTES,3,OUTRAS DESPESAS CORRENTES,90,APLICACOES DIRETAS,MU,Múltiplo,"2000,00","2000,00","1,0000"
0,180006000012019OB800099,2019OB800099,02/01/2019,OB,Ordem Bancária,OBC/OBB PARA TERCEIROS EM OUTROS BANCOS,NÃO,55000,MINISTERIO DA CIDADANIA,55000,...,DESPESAS DE CAPITAL,4,INVESTIMENTOS,40,TRANSFERENCIAS A MUNICIPIOS,42,AUXILIOS - FUNDO A FUNDO,"48750,00","48750,00","1,0000"
1,440075000012019DF800002,2019DF800002,02/01/2019,DF,Documento de Arrecadação Federal,Não se aplica,NÃO,22000,"MINIST. DA AGRICUL.,PECUARIA E ABASTECIMENTO",44208,...,DESPESAS CORRENTES,3,OUTRAS DESPESAS CORRENTES,90,APLICACOES DIRETAS,39,OUTROS SERVICOS DE TERCEIROS-PESSOA JURIDICA,"50,03","50,03","1,0000"
2,180006000012019OB800271,2019OB800271,02/01/2019,OB,Ordem Bancária,OBC/OBB PARA TERCEIROS EM OUTROS BANCOS,NÃO,55000,MINISTERIO DA CIDADANIA,55000,...,DESPESAS DE CAPITAL,4,INVESTIMENTOS,40,TRANSFERENCIAS A MUNICIPIOS,42,AUXILIOS - FUNDO A FUNDO,"204750,00","204750,00","1,0000"
3,158591264272019OB800001,2019OB800001,02/01/2019,OB,Ordem Bancária,OBS DE OUTRAS CONTAS PARA CONTA UNICA,NÃO,26000,MINISTERIO DA EDUCACAO,26427,...,Sem informação,-1,Sem informação,-1,Sem informação,-1,Sem informação,"-100,00","-100,00","1,0000"

In [7]:
# Trocando o tipo das colunas de object para float
col_numerica = ['Valor_original_do_pagamento','Valor_do_pagamento_convertido_pra_r$','Valor_utilizado_na_conversao']

# Fazendo essa troca nas 3 colunas
for col in col_numerica:
    df[col] = df[col].str.replace(',','.').astype('float')

# Verificando se a troca funcionou
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 388884 entries, 0 to 25850
Data columns (total 30 columns):
Codigo_pagamento                        388884 non-null object
Codigo_pagamento_resumido               388884 non-null object
Data_emissao                            388884 non-null object
Codigo_tipo_documento                   388884 non-null object
Tipo_documento                          388884 non-null object
Tipo_ob                                 388884 non-null object
Extraorcamentario                       388884 non-null object
Codigo_orgao_superior                   388884 non-null int64
Orgao_superior                          388884 non-null object
Codigo_orgao                            388884 non-null int64
Orgao                                   388884 non-null object
Codigo_unidade_gestora                  388884 non-null int64
Unidade_gestora                         388884 non-null object
Codigo_gestao                           388884 non-null int64
Gestao                                  388884 non-null object
Codigo_favorecido                       388884 non-null object
Favorecido                              388884 non-null object
Observacao                              388884 non-null object
Processo                                357946 non-null object
Codigo_categoria_de_despesa             388884 non-null object
Categoria_de_despesa                    388884 non-null object
Codigo_grupo_de_despesa                 388884 non-null object
Grupo_de_despesa                        388884 non-null object
Codigo_modalidade_de_aplicacao          388884 non-null object
Modalidade_de_aplicacao                 388884 non-null object
Codigo_elemento_de_despesa              388884 non-null object
Elemento_de_despesa                     388884 non-null object
Valor_original_do_pagamento             388884 non-null float64
Valor_do_pagamento_convertido_pra_r$    388884 non-null float64
Valor_utilizado_na_conversao            388884 non-null float64
dtypes: float64(3), int64(4), object(23)
memory usage: 92.0+ MB

In [13]:
# Agora irei remover todas as colunas com o nome codigo embutido no nome.
df = df.drop([x for x in df.columns if x.count('Codigo')], axis = 1)

In [21]:
# Após limpar as colunas irei substituir todos os valores ausentes da coluna 'Processo'.
df = df.fillna({'Processo':'Sem processo'})

In [22]:
# Banco de dados tratado e pronto para ser analisado.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 388884 entries, 0 to 25850
Data columns (total 18 columns):
Data_emissao                            388884 non-null object
Tipo_documento                          388884 non-null object
Tipo_ob                                 388884 non-null object
Extraorcamentario                       388884 non-null object
Orgao_superior                          388884 non-null object
Orgao                                   388884 non-null object
Unidade_gestora                         388884 non-null object
Gestao                                  388884 non-null object
Favorecido                              388884 non-null object
Observacao                              388884 non-null object
Processo                                388884 non-null object
Categoria_de_despesa                    388884 non-null object
Grupo_de_despesa                        388884 non-null object
Modalidade_de_aplicacao                 388884 non-null object
Elemento_de_despesa                     388884 non-null object
Valor_original_do_pagamento             388884 non-null float64
Valor_do_pagamento_convertido_pra_r$    388884 non-null float64
Valor_utilizado_na_conversao            388884 non-null float64
dtypes: float64(3), object(15)
memory usage: 56.4+ MB

In [23]:
# Salvando arquivo modificado em formato csv.
#df.to_csv('pagamentos_janeiro.csv')